### PR TITLE
Fix undeclared custom_table variable.

### PR DESCRIPTION
**Pull request by hawkfish**
**Things To Remember:** 

1. Be sure to merge into the right branch. The choices are:
* **`master`** if your PR runs on the current version of Tableau.
* **`dev-2021.2`**  
2. You should update at least one of the following:
* The changelog of the project you modified.
* The root `README.md` if the PR is a release of the SDK, Connector Packager, or TDVT.  
=====

### CODE REVIEW

**Comment by lukewrites** [comment]
Thanks for the PR, @hawkfish - did you try clicking through the SLA bot workflow? It is showing `cla: missing`, but they've been having trouble with the bot. Just let me know here if you've already done it.

Thanks!

**Comment by hawkfish** [comment]
Hey Luke - 

I’m not an employee - I just wrote the original dialect system when I was at Tableau back in the day. I’m hacking on DuckDB these days and I have another client who may be using it with Tableau to visualise a lot of hive-partitioned parquet files so I’m building out an official connector. My email is listed in my GitHub profile ***@***.*** as well as ***@***.***). HTH.
— 
Best regards,
Richard Wesley

Our opponent is an alien starship packed with atomic bombs. We have a protractor. 
  ― Neal Stephenson, Anathem

**Comment by lukewrites** [comment]
Hi, Richard,

It's nice to see you here after seeing your name pop up in the source so often 😄 The SLA thing is a workflow Salesforce requires of internal and external contributors to their repos. But like I mentioned, it's flaky, so if someone says they've done it we take them at their word 😄 

Thanks again for the bug fix, sorry I missed that commit when I merged this.

**Review by lukewrites — APPROVED** [review]
Thanks @hawkfish

**Comment by hawkfish** [comment]
Hey Luke -

I’m trying to install a self-signed cert <https://tableau.github.io/connector-plugin-sdk/docs/log-entries#import-a-certificate-to-the-trusted-keystore> for testing on my MacBook, but there doesn’t seem to be any JRE. It looks like Tableau includes a JRE but I can’t write to that.

Here’s what I’ve been doing:

keytool -genkey -keyalg RSA -alias duckdb_taco -keystore keystore.jks -storepass <password> -validity 360 -keysize 2048
jarsigner -keystore keystore.jks -storepass <password> -verbose ~/duckdb_jdbc.taco duckdb_taco
keytool -exportcert -alias duckdb_taco -keystore keystore.jks -storepass <password> -file duckdb_taco.cer
keytool -importcert -file duckdb_taco.cer -keystore ??? -storepass ??? -alias duckdb_taco

What goes in the blanks? 
— 
Best regards,
Richard Wesley

I am a magnet for all kinds of deeper wonderment.
  — Alanis Morissette, Wunderkind

**Pull request merged**
