### PR TITLE
Packaging jshah

### PR DESCRIPTION
**Pull request by pvanderknyff**
This didn't get merged into dev, but it looks like the branch was never deleted, so I can just merge that into dev.

### CODE REVIEW

**Comment by jainam1995** [comment]
A small query : Wouldnt the correct approach be to merge packaging branch (https://github.com/tableau/connector-plugin-sdk/tree/packaging) which has this change to master ?

**Comment by pvanderknyff** [comment]
> A small query : Wouldnt the correct approach be to merge packaging branch (https://github.com/tableau/connector-plugin-sdk/tree/packaging) which has this change to master ?

I think there might be conflicts. The packaging branch is basically deprecated at this point, and there may be commits we don't really want, or commits that are already there. Probably why this change never got picked up.

**Comment by rosswbrown** [comment]
Can we remove the packaging branch after this change is merged?  Maybe some other branch cleanup if possible.

**Comment by lukewrites** [comment]
> 
> 
> Can we remove the packaging branch after this change is merged? Maybe some other branch cleanup if possible.

good idea.

**Pull request merged**
