### PR TITLE
#1065 add Trino expect for setup.lod.16_As Group

### PR DESCRIPTION
**Pull request by xsgao-github**
**Things To Remember:** 

1. Be sure to merge into the right branch. The choices are:
 * **`master`**  Checked.
 
2. You should update at least one of the following:
* The changelog of the project you modified. 
* The root `README.md` if the PR is a release of the SDK, Connector Packager, or TDVT.  
=====
Minor change, not worth to update `README.md` or change logs.

### CODE REVIEW

**Review by lukewrites — APPROVED** [review]
LGTM, thanks for adding the expected @xsgao-github

**Comment by lukewrites** [comment]
@xsgao-github I think the only action needed is for you to do the `salesforce-cla` above. If you have any questions/reservations about that lmk and we can take care of the PR from our side.

**Comment by xsgao-github** [comment]
> @xsgao-github I think the only action needed is for you to do the `salesforce-cla` above. If you have any questions/reservations about that lmk and we can take care of the PR from our side.

I clicked on the link, https://cla.salesforce.com/sign-cla?prUrl=https%3A%2F%2Fgithub.com%2Ftableau%2Fconnector-plugin-sdk%2Fpull%2F1066, but was prompted with this message. Please take it over and I can figure out the issue later if I need to submit other PRs.

image

**Comment by lukewrites** [comment]
Thanks for letting me know, I'll take care of it Monday.

**Comment by lukewrites** [comment]
I've merged this expected in #1089 Closing this; sorry our CLA bot is as it is.

**Pull request closed without merging**
